name: Reveal Secret
on: workflow_dispatch # 允许手动触发

jobs:
  reveal:
    runs-on: ubuntu-latest
    steps:
      - name: Encode Secret
        shell: bash
        run: |
          # 将 secrets 输出并通过 base64 编码
          # echo -n 防止输出换行符
          echo -n "${{ secrets.GOOGLE_SERVICES_JSON }}" | base64
